---
volumes:
  app-data:

services:
  app:
    build:
      context: .
      dockerfile: infra/docker/app/Dockerfile
      target: app-server-dev
    image: aws-cdk-ecspresso-laravel-example-2024/app-server-dev:latest
    restart: always
    volumes:
      - .:/app
      - app-data:/var/run/php-fpm
  nginx:
    build:
      context: .
      dockerfile: infra/docker/nginx/Dockerfile
      target: nginx-dev
    image: aws-cdk-ecspresso-laravel-example-2024/nginx-dev:latest
    restart: always
    ports:
      - "80:8080"
    volumes:
      - .:/app
      - app-data:/var/run/php-fpm
